# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZyboZ7Pins.xdc

# Block Designs: bd/ControllerBD/ControllerBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD || ORIG_REF_NAME==ControllerBD} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_processing_system7_0_0/ControllerBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_processing_system7_0_0 || ORIG_REF_NAME==ControllerBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_ps7_0_axi_periph_0/ControllerBD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_ps7_0_axi_periph_0 || ORIG_REF_NAME==ControllerBD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_rst_ps7_0_50M_0/ControllerBD_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_rst_ps7_0_50M_0 || ORIG_REF_NAME==ControllerBD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_clk_wiz_0_0/ControllerBD_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_clk_wiz_0_0 || ORIG_REF_NAME==ControllerBD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_PWM_Writer_8CH_50HZ_0_0/ControllerBD_PWM_Writer_8CH_50HZ_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_PWM_Writer_8CH_50HZ_0_0 || ORIG_REF_NAME==ControllerBD_PWM_Writer_8CH_50HZ_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_PWM_Reader_8CH_0_0/ControllerBD_PWM_Reader_8CH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_PWM_Reader_8CH_0_0 || ORIG_REF_NAME==ControllerBD_PWM_Reader_8CH_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_axi_gpio_0_0/ControllerBD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_axi_gpio_0_0 || ORIG_REF_NAME==ControllerBD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_axi_uartlite_0_0/ControllerBD_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_axi_uartlite_0_0 || ORIG_REF_NAME==ControllerBD_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_axi_uartlite_1_0/ControllerBD_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_axi_uartlite_1_0 || ORIG_REF_NAME==ControllerBD_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_axi_uartlite_2_0/ControllerBD_axi_uartlite_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_axi_uartlite_2_0 || ORIG_REF_NAME==ControllerBD_axi_uartlite_2_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_xlconcat_0_0/ControllerBD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_xlconcat_0_0 || ORIG_REF_NAME==ControllerBD_xlconcat_0_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_axi_gpio_1_0/ControllerBD_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_axi_gpio_1_0 || ORIG_REF_NAME==ControllerBD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_xbar_0/ControllerBD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_xbar_0 || ORIG_REF_NAME==ControllerBD_xbar_0} -quiet] -quiet

# IP: bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ControllerBD_auto_pc_0 || ORIG_REF_NAME==ControllerBD_auto_pc_0} -quiet] -quiet

# XDC: bd/ControllerBD/ControllerBD_ooc.xdc
