# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.cache/wt [current_project]
set_property parent.project_path /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /media/sf_Projects-shared/ZynqRobotController/FPGA/ip_repo/PWM_Reader_8CH_2.0
  /media/sf_Projects-shared/ZynqRobotController/FPGA/ip_repo/PWM_Writer_8CH_50HZ_2.0
  /media/sf_Projects-shared/ZynqRobotController/FPGA/ip_repo/AXI_PWM_Writer_8CH_50HZ_1.0
  /media/sf_Projects-shared/ZynqRobotController/FPGA/ip_repo/AXI_PWM_Reader_8CH_1.0
  /home/tjlw/ip_repo
  /home/tjlw/ip_repo/ParallaxPingSensor/ParallaxPingSensor_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/hdl/ControllerBD_wrapper.vhd
  /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/new/Top.vhd
}
add_files /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ControllerBD.bd
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_processing_system7_0_0/ControllerBD_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_rst_ps7_0_50M_0/ControllerBD_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_rst_ps7_0_50M_0/ControllerBD_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_rst_ps7_0_50M_0/ControllerBD_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_clk_wiz_0_0/ControllerBD_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_clk_wiz_0_0/ControllerBD_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_clk_wiz_0_0/ControllerBD_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_0_0/ControllerBD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_0_0/ControllerBD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_0_0/ControllerBD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_0_0/ControllerBD_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_0_0/ControllerBD_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_0_0/ControllerBD_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_1_0/ControllerBD_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_1_0/ControllerBD_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_1_0/ControllerBD_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_2_0/ControllerBD_axi_uartlite_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_2_0/ControllerBD_axi_uartlite_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_uartlite_2_0/ControllerBD_axi_uartlite_2_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_1_0/ControllerBD_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_1_0/ControllerBD_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_axi_gpio_1_0/ControllerBD_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_xbar_0/ControllerBD_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ControllerBD_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/constrs_1/new/ZyboZ7Pins.xdc
set_property used_in_implementation false [get_files /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/constrs_1/new/ZyboZ7Pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
