# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pins.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/System/System_ooc.xdc
