# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0.xci
# IP: The module: 'ControllerBD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ControllerBD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0.xci
# IP: The module: 'ControllerBD_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_Projects-shared/ZynqRobotController/FPGA/Zynq_Robot_Controller_v2/Zynq_Robot_Controller.srcs/sources_1/bd/ControllerBD/ip/ControllerBD_auto_pc_0/ControllerBD_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ControllerBD_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
