# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
# IP: The module: 'System_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
# IP: The module: 'System_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/sf_Projects/ZynqRobotController/FPGA/IP/ZyboZ710_PWM_Passthrough/ZyboZ710_PWM_Passthrough.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
